twig:
    default_path: '%kernel.project_dir%/templates'
    paths: 
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/css': css
when@test:
    twig:
        strict_variables: true

    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
